ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****
image::3-BusinessContext.drawio.svg["Business context diagram"]


**Table for entities, inputs and outputs**

|===  
|Entity |Inputs | Outputs

|*_User Interface UI_*
|Users request a question to be shown 
|The question and the set of answers corresponding to that question are presented
|*_Question Generation_*
|User requests a question and the information extracted from wikidata
|The question and the set of answers corresponding to that question are created
|*_Wikidata API_*
|Some part or topic related to the creation of a question
|Some concepts that will facilitate the creation of the question such as wrong answers
|===

=== Technical Context

[role="arc42help"]

****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****
image::3-TechnicalContext.drawio.svg["Business context diagram"]
.User And Application interface +
The user will access the web application via the HTTPs protocol

.Home and Login interface +
The home will allow user to be redirected to the login and authentication phase via the HTTPs protocol

.Login and Question Generation interface +
The login will allow the user to enter the game and so the question generation will start, this will happend through a redirect

.Login and Database +
The login will access the database directly via TCP/IP protocol


