ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
=== Technology decisions

The technologies chosen for developing the WIQ web app are ::
* **Java** : Java is a high-level, object-oriented programming language developed by Sun Microsystems. It is known for its portability, security features, and wide range of applications, from mobile to enterprise systems.

* **Nodejs** : Node.js is an open-source, cross-platform JavaScript runtime environment that executes JavaScript code outside of a web browser, allowing developers to build scalable network applications.

* **ReactJS** : A JavaScript library that facilitates the creation of interactive grafical interfaces.

* **Wikidata Toolkit** : Wikidata Toolkit is a Java library for accessing Wikidata and other Wikibase installations. It can be used to create bots, to perform data extraction tasks (e.g., convert all data in Wikidata to a new format), and to do large-scale analyses that are too complex for using a simple SPARQL query service.

* **Express** : Express is a minimal and flexible Node.js web application framework that provides a robust set of features for building web and mobile applications.

* **Mongo DB** : MongoDB is a popular open-source NoSQL database management system that stores data flexible, JSON-like documents with dynamic schemas.

* **Docker** : Docker provides tools and a runtime environment to manage these containers efficiently, allowing developers to build, ship, and run applications consistently across different environments.


This decisions were eventually discarded ::
* **Sass** : A scripting language that is compiled into CSS. It extends CSS by providing several mechanisms such as variables, nested rules, mixins, functions, and inheritance.

* **TypeScript** : A superset of JavaScript that adds various features that can resolve code errors before running the actual code.

* **SpringBoot** : An extension of the Spring framework for creating Java applications. SpringBoot offers many preconfigurations that accelerate the code production process.

* **MySql** : MySQL is an open-source relational database management system that uses SQL for managing and manipulating data.


=== Top-level Decomposition

To be updated along the development of the application where we will add the most important architectural and design patterns

==== Architectural Patterns

* **Microservices** : Selected as our main architecture. We will have various small independent services that interact between them to support all the fuctionalities of the web application.

* **API Gateway** : This API gateway serves as a centralized point for managing, securing, and routing requests between clients and multiple backend services or APIs. This is applied to centralized the calls to the different microservices.

* **Shared data** : An architectural pattern used to communicate two services through a data repository. In our case, we will communicate the questions generator and the game through a database for a better efficiency and robustness.

==== Design Patterns

* **Façade** : Pattern used to communicate between different parts of the whole application (APIs).
* **Template** : Pattern used to set some fixed steps of an algorithm. This was used for the different questions generators.

=== Decisions for achieving quality goals

|===
|Quality Goal|Decision
| _Usability_ | _We will try to make some rounds of usability tests with people outside of the development team_
| _Performance_ | _Our goal is to have a system that will response under 1 second to all petitions, however the consecuences of peak times are unknow_
| _Security_ | _Using HTTPS, applying input validation, encripting sensible information (As we face new security failures we will add measures)_
| _Robustness_ | _We will apply different mechanism to reduce the risks that could crash the application_
| _Accesibility_ | _Testing our User Interface with third party tools like Google's Lighthouse in order to correct them_
|===

Will be updated whenever we find a new quality goal or we change the approach to achieve it

=== Organizational Decisions

|===
|Third Party Product|Reason
| _Git_ | _Easy to use distributed version control application_
| _Github_ | _Web-based platform for hosting and managing Git repositories. It also provides different services like: a wiki, issues, github actions and many more_
| _Microsoft Azure_ | _Cloud service use for creating virtual machines in order to deploy the application_
|===