ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
=== Technology decisions

The technologies chosen for developing the WIQ web app are ::
* **ReactJS** : A JavaScript library that facilitates the creation of interactive grafical interfaces.
* **Sass** : A scripting language that is compiled into CSS. It extends CSS by providing several mechanisms such as variables, nested rules, mixins, functions, and inheritance. 
* **TypeScript** : A superset of JavaScript that adds various features that can resolve code errors before running the actual code.
* **SpringBoot** : An extension of the Spring framework for creating Java applications. SpringBoot offers many preconfigurations that accelerate the code production process.
* **Wikidata access library** :
* **Docker** :
* **Oracle DBMS** : 
* **Mongo DB** : 

=== Top-level Decomposition

To be updated along the development of the application where we will add the most important architectural and design patterns

==== Architectural Patterns

* **Microservices** : Selected as our main architecture. We will have various small independent services that interact between them to support all the fuctionalities of the web application

==== Design Patterns

* **Façade** : Pattern used to communicate between different parts of the whole application (APIs)

=== Decisions for achieving quality goals

Will be updated whenever we find a new quality goal or we change the approach to achieve it

=== Organizational Decisions

