ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Architecture Decisions
The application will be carried out following a Microservices architecture. +

The service in charge of comunicating with WikiData will be coded using Java. 
As the generation of questions is a huge part of our application we will play it safe by using Java, a language where most of the team is "fluent" at. +

The backend will we develop using a combination of SpringBoot, for the question generation, and Express.
The use of SpringBoot was a requirement in order to generate the questions in Java. +

*10/03/24* 

We will apply a data share strategy where we will load the questions generated and access them when needed through the backend.
This is done to increase the efficiency, as questions are not generated when needed, and robustness of the application, as we can give service even if Wikidata is down. +

*14/03/24*

We have done a redisign of the architecture of the project where we will implement the whole backend using Express.
This was done to have a more homogeneus backend as we have de-coupled the question generation from the backend and we dont need all to be Java. +


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****
